import type { Metadata } from "next";
import { Jost, Nunito } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from '@/lib/react-query';
import {Toaster} from 'sonner'
const JostFont = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const NunitoFont = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${JostFont.variable} ${NunitoFont.variable} antialiased`}
      >
        <ReactQueryProvider>
        {children}
        </ReactQueryProvider>
        <Toaster richColors/>
      </body>
    </html>
  );
}
